#!/usr/bin/env node
// Assemble the deployable app into dist/ for Cloudflare Pages.
//
//   node tools/build-pages.mjs        (or: npm run build:pages)
//
// Why this exists rather than pointing Pages at the repository root:
//
// With the root as the build output directory, a deployment carries everything
// in the repo — server.js, server.pl, the whole tools/ tree (hamlib-sources.json
// alone is ~1 MB), docs/, the whole test/ tree — and serves all of it publicly. None
// of it is needed to run WebHam, and "the repository is public anyway" is not a
// reason to publish a second copy at the app's own origin: the deployment is the
// attack surface people actually probe, and a static host that answers for
// server.js invites someone to look for a version that answers for more.
//
// So: an explicit allowlist of what the browser actually loads. Anything not
// named here does not ship, which also means a new runtime file has to be added
// deliberately — and check.sh fails if one is missed (see below).
//
// functions/ is NOT copied. Cloudflare finds Pages Functions at the repository
// root regardless of the build output directory, so it must stay where it is.
import { cp, mkdir, rm, readFile, readdir, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DIST = join(ROOT, "dist");

// Everything the running app fetches. Directories are copied whole.
export const SHIP = [
  "index.html",
  "404.html",
  "styles.css",
  "manifest.webmanifest",
  "sw.js",
  // Pages reads these from the build output directory, not the repo root.
  "_headers",
  "_routes.json",
  "js",
  "vendor",
  // Generated by tools/make-icons.mjs. Without these the manifest has no icons
  // and Chromium silently declines to offer "Install app".
  "icons",
];

// Present in the repo, deliberately not deployed. Listed by name so the intent
// is explicit and so the check below can prove none of them leaked into dist/.
export const DO_NOT_SHIP = [
  "server.js", "server.pl", "start-server.sh", "start-server.ps1",
  "package.json", "check.sh", "README.md", "FOLLOWUPS.md",
  "tools", "docs", "test", ".github", ".agents", ".codex",
];

export async function buildPages({ quiet = false } = {}) {
  const say = (m) => { if (!quiet) process.stdout.write(`${m}\n`); };

  await rm(DIST, { recursive: true, force: true });
  await mkdir(DIST, { recursive: true });

  const missing = [];
  for (const entry of SHIP) {
    const from = join(ROOT, entry);
    if (!existsSync(from)) { missing.push(entry); continue; }
    await cp(from, join(DIST, entry), { recursive: true });
  }
  if (missing.length) {
    throw new Error(`build-pages: missing required files: ${missing.join(", ")}`);
  }

  // Every module the service worker promises to precache has to exist in the
  // build, or an offline load fetches a miss and the module graph never
  // resolves. check.sh already proves sw.js matches `git ls-files`; this proves
  // the same list survived the copy.
  const sw = await readFile(join(DIST, "sw.js"), "utf8");
  // Keep this extension list in step with what sw.js precaches. It silently
  // skipped the app icons until png was added — an unverified entry is worse
  // than no check, because the "all present" line implies coverage it lacks.
  const precached = [
    ...sw.matchAll(/"(\/[^"]+\.(?:js|wasm|css|html|webmanifest|png|svg|ico))"/g),
  ].map((m) => m[1]);
  const absent = [];
  for (const path of new Set(precached)) {
    if (path === "/") continue;
    if (!existsSync(join(DIST, path.slice(1)))) absent.push(path);
  }
  if (absent.length) {
    throw new Error(`build-pages: sw.js precaches files not in the build: ${absent.join(", ")}`);
  }

  let bytes = 0, files = 0;
  const walk = async (dir) => {
    for (const e of await readdir(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) await walk(p);
      else { files += 1; bytes += (await stat(p)).size; }
    }
  };
  await walk(DIST);

  say(`Built dist/ — ${files} files, ${(bytes / 1024).toFixed(0)} KB`);
  say(`  precache verified: ${new Set(precached).size} entries all present`);
  return { files, bytes, precached: new Set(precached).size };
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  buildPages().catch((error) => {
    process.stderr.write(`${error.message}\n`);
    process.exit(1);
  });
}
